version: "3.8"

x-environment: &environment
  environment:
    - TZ=$TZ
    - PUID=$PUID
    - PGID=$PGID

services:
  datadog:
    image: datadog/agent:latest
    container_name: datadog-agent
    environment:
     - DD_API_KEY=$DATADOG_API_KEY
     - DD_PROCESS_AGENT_PROCESS_COLLECTION_ENABLED=true
     - DD_AGENT_HOST=dd-agent
     - DD_SITE=us5.datadoghq.com
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /proc/:/host/proc/:ro
     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
