version: "3.8"

x-environment: &environment
  environment:
    - TZ=$TZ
    - PUID=$PUID
    - PGID=$PGID

services:
  datadog:
    image: datadog/agent:latest
    container_name: datadog-agent
    environment:
     - DD_API_KEY=$DATADOG_API_KEY
     - DD_PROCESS_AGENT_PROCESS_COLLECTION_ENABLED=true
     - DD_AGENT_HOST=dd-agent
     - DD_SITE=us5.datadoghq.com
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /proc/:/host/proc/:ro
     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro

  unifi-controller:
    image: lscr.io/linuxserver/unifi-controller:latest
    container_name: unifi-controller
    restart: unless-stopped
    <<: [*environment]
    volumes:
      - $APPS_DIR/unifi:/config
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8082:8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.unifi.entrypoints=websecure"
      - "traefik.http.routers.unifi.rule=Host(`unifi.${PUBLIC_HOSTNAME}`)"
      - "traefik.http.routers.unifi.tls=true"
      - "traefik.http.routers.unifi.service=unifi"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.services.unifi.loadbalancer.server.port=8443"
      - "traefik.http.services.unifi.loadbalancer.server.scheme=https"
    pull_policy: always